<?php

namespace Proxies\__CG__\League\Bundle\OAuth2ServerBundle\Model;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \League\Bundle\OAuth2ServerBundle\Model\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'identifier'];
        }

        return ['__isInitialized__', 'identifier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \League\Bundle\OAuth2ServerBundle\Model\AbstractClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier(): string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdentifier();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', []);

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getSecret(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecret', []);

        return parent::getSecret();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedirectUris(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedirectUris', []);

        return parent::getRedirectUris();
    }

    /**
     * {@inheritDoc}
     */
    public function setRedirectUris(\League\Bundle\OAuth2ServerBundle\Model\RedirectUri ...$redirectUris): \League\Bundle\OAuth2ServerBundle\Model\AbstractClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRedirectUris', [$redirectUris]);

        return parent::setRedirectUris(...$redirectUris);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrants(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrants', []);

        return parent::getGrants();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrants(\League\Bundle\OAuth2ServerBundle\Model\Grant ...$grants): \League\Bundle\OAuth2ServerBundle\Model\AbstractClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrants', [$grants]);

        return parent::setGrants(...$grants);
    }

    /**
     * {@inheritDoc}
     */
    public function getScopes(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScopes', []);

        return parent::getScopes();
    }

    /**
     * {@inheritDoc}
     */
    public function setScopes(\League\Bundle\OAuth2ServerBundle\Model\Scope ...$scopes): \League\Bundle\OAuth2ServerBundle\Model\AbstractClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScopes', [$scopes]);

        return parent::setScopes(...$scopes);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): \League\Bundle\OAuth2ServerBundle\Model\AbstractClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function isConfidential(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isConfidential', []);

        return parent::isConfidential();
    }

    /**
     * {@inheritDoc}
     */
    public function isPlainTextPkceAllowed(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPlainTextPkceAllowed', []);

        return parent::isPlainTextPkceAllowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowPlainTextPkce(bool $allowPlainTextPkce): \League\Bundle\OAuth2ServerBundle\Model\AbstractClient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowPlainTextPkce', [$allowPlainTextPkce]);

        return parent::setAllowPlainTextPkce($allowPlainTextPkce);
    }

}
