<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3XBt2yPService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.service_locator.3XBt2yP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3XBt2yP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['privates', '.errored..service_locator.3XBt2yP.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.3XBt2yP": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
        ], [
            'em' => 'Doctrine\\ORM\\EntityManager',
        ]);
    }
}
