<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kc70PkCService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.service_locator.Kc70PkC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kc70PkC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Member' => ['privates', '.errored..service_locator.Kc70PkC.Eccube\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.Kc70PkC": it references class "Eccube\\Entity\\Member" but no such service exists.'],
        ], [
            'Member' => 'Eccube\\Entity\\Member',
        ]);
    }
}
