<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PreNChpService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.service_locator.PreNChp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PreNChp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Payment' => ['privates', '.errored..service_locator.PreNChp.Eccube\\Entity\\Payment', NULL, 'Cannot autowire service ".service_locator.PreNChp": it references class "Eccube\\Entity\\Payment" but no such service exists.'],
        ], [
            'Payment' => 'Eccube\\Entity\\Payment',
        ]);
    }
}
