<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvTypeService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.c7srIbq.Eccube\Entity\Master\CsvType' shared service.
     *
     * @return \Eccube\Entity\Master\CsvType
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.c7srIbq": it references class "Eccube\\Entity\\Master\\CsvType" but no such service exists.');
    }
}
