<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.lYl_n6Z.Eccube\Entity\Delivery' shared service.
     *
     * @return \Eccube\Entity\Delivery
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lYl_n6Z": it references class "Eccube\\Entity\\Delivery" but no such service exists.');
    }
}
