<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.7gvD0iZ.Eccube\Entity\News' shared service.
     *
     * @return \Eccube\Entity\News
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7gvD0iZ": it references class "Eccube\\Entity\\News" but no such service exists.');
    }
}
