<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.ca0q2bl.Eccube\Entity\Order' shared service.
     *
     * @return \Eccube\Entity\Order
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ca0q2bl": it references class "Eccube\\Entity\\Order" but no such service exists.');
    }
}
