<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.ZAltsdx.Eccube\Entity\Plugin' shared service.
     *
     * @return \Eccube\Entity\Plugin
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZAltsdx": it references class "Eccube\\Entity\\Plugin" but no such service exists.');
    }
}
