<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductStatusService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.ppQSDYx.Eccube\Entity\Master\ProductStatus' shared service.
     *
     * @return \Eccube\Entity\Master\ProductStatus
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ppQSDYx": it references class "Eccube\\Entity\\Master\\ProductStatus" but no such service exists.');
    }
}
