<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShipping2Service extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.VI5YnIL.Eccube\Entity\Shipping' shared service.
     *
     * @return \Eccube\Entity\Shipping
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VI5YnIL": it references class "Eccube\\Entity\\Shipping" but no such service exists.');
    }
}
