<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxRuleService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator...YR0_q.Eccube\Entity\TaxRule' shared service.
     *
     * @return \Eccube\Entity\TaxRule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator...YR0_q": it references class "Eccube\\Entity\\TaxRule" but no such service exists.');
    }
}
