<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.F0YSA_7.Eccube\Entity\Tag' shared service.
     *
     * @return \Eccube\Entity\Tag
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.F0YSA_7": it references class "Eccube\\Entity\\Tag" but no such service exists.');
    }
}
