<?php

namespace ContainerVTFAYMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateService extends Eccube_KernelInstallContainer
{
    /*
     * Gets the private '.errored..service_locator.r0PTHNW.Eccube\Entity\Template' shared service.
     *
     * @return \Eccube\Entity\Template
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.r0PTHNW": it references class "Eccube\\Entity\\Template" but no such service exists.');
    }
}
