<?php

namespace ContainerJeLjmue;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LYlN6ZService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.lYl_n6Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lYl_n6Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Delivery' => ['privates', '.errored..service_locator.lYl_n6Z.Eccube\\Entity\\Delivery', NULL, 'Cannot autowire service ".service_locator.lYl_n6Z": it references class "Eccube\\Entity\\Delivery" but no such service exists.'],
        ], [
            'Delivery' => 'Eccube\\Entity\\Delivery',
        ]);
    }
}
