<?php

namespace ContainerJeLjmue;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OKBEma5Service extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.OKBEma5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OKBEma5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Product' => ['privates', '.errored..service_locator.OKBEma5.Eccube\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.OKBEma5": it references class "Eccube\\Entity\\Product" but no such service exists.'],
            'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService', true],
        ], [
            'Product' => 'Eccube\\Entity\\Product',
            'cacheUtil' => 'Eccube\\Util\\CacheUtil',
        ]);
    }
}
