<?php

namespace ContainerJeLjmue;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PpQSDYxService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ppQSDYx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ppQSDYx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ProductStatus' => ['privates', '.errored..service_locator.ppQSDYx.Eccube\\Entity\\Master\\ProductStatus', NULL, 'Cannot autowire service ".service_locator.ppQSDYx": it references class "Eccube\\Entity\\Master\\ProductStatus" but no such service exists.'],
            'cacheUtil' => ['privates', 'Eccube\\Util\\CacheUtil', 'getCacheUtilService', true],
        ], [
            'ProductStatus' => 'Eccube\\Entity\\Master\\ProductStatus',
            'cacheUtil' => 'Eccube\\Util\\CacheUtil',
        ]);
    }
}
