<?php

namespace ContainerJeLjmue;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator___YR0QService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator...YR0_q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator...YR0_q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'TaxRule' => ['privates', '.errored..service_locator...YR0_q.Eccube\\Entity\\TaxRule', NULL, 'Cannot autowire service ".service_locator...YR0_q": it references class "Eccube\\Entity\\TaxRule" but no such service exists.'],
        ], [
            'TaxRule' => 'Eccube\\Entity\\TaxRule',
        ]);
    }
}
