<?php

namespace ContainerJeLjmue;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F9ADkqWService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.F9ADkqW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F9ADkqW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Calendar' => ['privates', '.errored..service_locator.F9ADkqW.Eccube\\Entity\\Calendar', NULL, 'Cannot autowire service ".service_locator.F9ADkqW": it references class "Eccube\\Entity\\Calendar" but no such service exists.'],
        ], [
            'Calendar' => 'Eccube\\Entity\\Calendar',
        ]);
    }
}
