<?php

namespace ContainerJeLjmue;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlockService extends Eccube_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.LuO12gx.Eccube\Entity\Block' shared service.
     *
     * @return \Eccube\Entity\Block
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LuO12gx": it references class "Eccube\\Entity\\Block" but no such service exists.');
    }
}
